#!/bin/bash
#
# File managed by Puppet
#

source /opt/graphite/graphite_functions

### Code to generate metrics

### Use imported send function to send metric eg.
###    send "$PREFIX.memory.total" "$MEM"
