#!/usr/bin/php
<?php
error_reporting(0);

// THIS IS A TEMPLATE FOR CREATING GRAPHITE CHECKS

if(isset($_SERVER['argv'][1])) $graphiteServer = $_SERVER['argv'][1];
else $graphiteServer = "graphite.silverstripe.com";

if(isset($_SERVER['argv'][2])) $graphitePort = $_SERVER['argv'][2];
else $graphitePort = "2003";

// Get the server name and server group from FQDN
list($serverName, $serverGroup) = explode(".", trim(`hostname -f`));

// STEP 1: PUT ANY CODE FOR COLLECTING STATS HERE
// Eg:
// $numProcesses = `ps aux | wc -l`

$stats = array();

// STEP 2: PUT YOUR STAT DEFINITIONS HERE.
// EG:
// $stats["server.$serverGroup.$serverName.processes.count"] = $numProcesses; 

// Write data
$socket = fsockopen($graphiteServer, $graphitePort);
$time = time();
foreach($stats as $key => $value) {
	fwrite($socket, "$key $value $time\n");
	echo("$key $value $time\n");
}
fclose($socket);
