#!/bin/bash
#
# File managed by Puppet
#

source /opt/graphite/graphite_functions

# Generate Squid Data
squidclient -a -T 1 -p 8888 -h localhost cache_object://localhost/counters 2> /dev/null | while read -r LINE; do
  set -- $LINE

  if [[ $LINE == "client_http"* ]] || [[ $LINE == "server"* ]]; then
    send "$PREFIX.squid.$1" "$3"
  fi

done
